---
title: "Project Proposal"
author: " Rammstein "
date: "24 08 2020"
output: html_document
---

# "R"ammstein Project Proposal

Analzing the first marriage statistics in Turkey between 2009-2019 years for different genders, education levels and age groups.

## Group members

* Canan Kılıçkıran
* Ecemnaz Bay
* Yunus Emre Toprak
* Umut Mustafa Dilsiz
* Metin Yüksel Güngör
* Yusuf Beşiroğlu


## Data Explanation

Data is obtained from [TUIK site](https://biruni.tuik.gov.tr/medas/?kn=112&locale=tr). It contains numbers of first marriages between 2009-2019 years for different education levels and age groups.

Data has 2568 rows and 3 variables "education level", "age group" , "year" and "gender"

## Project Plan

1. Cleaning and formatting the data 
2. Exploration of the data
3. Analyze and visualize the data 
4. Overall, get insights from the data

## Objectives

1. Comparision of genders according to the number of their first marriage numbers 
2. Find the age groups that has maximum/minimum number of first marriages for each gender 
3. Find the education level that has maximum/minimum number of first marriages for each gender 
4. Explore the number of first marriages throughout the years

## References

https://biruni.tuik.gov.tr/medas/?kn=112&locale=tr

